version: "3.8"

services:
  
  frontend:
    build: ./furseal-frontend
    image: furseal-frontend:v1.7
    container_name: furseal-frontend
    ports:
      - 80:80
    environment:
      - BACKEND_BASE_PATH=http://furseal-backend:9000
    depends_on:
      - backend
      - mysqldb

    
  backend:
    build: ./furseal-backend
    image: furseal-backend:v1.8
    container_name: furseal-backend
    ports:
      - 9000:9000
    environment: 
      - APP_NAME=furseal-backend
    depends_on:
      - mysqldb

  mysqldb:
    image: amd64/mysql:latest
    container_name: furseal-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=Kyo77437743
      - MYSQL_DATABASE=furseal
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

#  keycloak:
#    image: jboss/keycloak:latest
#    #    image: jboss/keycloak:11.0.2
#    container_name: keycloak
#    ports:
#      - 8080:8080
#    environment:
#      - KEYCLOAK_USER=admin
#      - KEYCLOAK_PASSWORD=admin
#      - DB_VENDOR=postgres
#      - DB_ADDR=postgres
#      - DB_DATABASE=keycloak
#      - DB_USER=keycloak
#      - DB_PASSWORD=keycloak
#      - KEYCLOAK_IMPORT=/tmp/realm-test.json
#    volumes:
#      - ./infra/keycloak/realm-test.json:/tmp/realm-test.json
#    command: [ "-Dkeycloak.profile.feature.upload_scripts=enabled" ]
#    depends_on:
#      - postgre

#  postgres:
#    image: postgres:13.0-alpine
#    container_name: postgres
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    volumes:
#      - ./postgres:/var/lib/postgresql/data
#      - ./infra/postgres:/docker-entrypoint-initdb.d

#  prometheus:
#    image: prom/prometheus:v2.22.0
#    container_name: prometheus
#    ports:
#      - 5000:9090
#    volumes:
#      - prometheus:/prometheus
#      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

#  grafana:
#    image: grafana/grafana:6.7.5
#    container_name: grafana
#    ports:
#      - 3000:3000
#    environment:
#      - PROMETHEUS_URL=http://prometheus:9090
#      - DS_PROMETHEUS=prometheus
#    volumes:
#      - ./infra/grafana/config.ini:/etc/grafana/config.ini
#      - ./infra/grafana/provisioning:/etc/grafana/provisioning
#      - ./infra/grafana/dashboards:/var/lib/grafana/dashboards
#    depends_on:
#      - prometheus

#volumes:
#  postgres
#  prometheus:
volumes:
  mysql-data:
