apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2022-05-13T21:16:11Z"
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: furseal-frontend
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:externalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":80,"protocol":"TCP"}:
              .: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector:
            .: {}
            f:app: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: GoogleCloudConsole
      operation: Update
      time: "2022-05-13T21:16:11Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"service.kubernetes.io/load-balancer-cleanup": {}
        f:status:
          f:loadBalancer:
            f:ingress: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-05-13T21:16:56Z"
  name: furseal-frontend-service
  namespace: default
  resourceVersion: "82117"
  uid: 14379e07-2a92-4b6d-9c1a-c27556dd5422
spec:
  clusterIP: 10.113.130.35
  clusterIPs:
    - 10.113.130.35
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30787
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: furseal-frontend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 34.81.22.250
