apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: furseal-frontend2
  name: furseal-frontend2
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: furseal-frontend2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: furseal-frontend2
    spec:
      containers:
        - env:
            - name: BACKEND_BASE_PATH
              valueFrom:
                configMapKeyRef:
                  key: BACKEND_BASE_PATH
                  name: furseal-frontend-config-phgv
            - name: KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_URL
                  name: furseal-frontend-config-phgv
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_REALM
                  name: furseal-frontend-config-phgv
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_CLIENT_ID
                  name: furseal-frontend-config-phgv
          image: gcr.io/skilled-circle-350105/furseal-frontend@sha256:03470df5b56c3a596d4f9508e876ae33a48528b19a2513e3f3ef8fe70976c41a
          imagePullPolicy: IfNotPresent
          name: furseal-frontend2-sha256-1
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
            requests:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30

