spring:
  profiles:
#    active: dev
    active: @active-profiles@
  security:
    ignored: "/actuator/**"
#  datasource:
#    url: jdbc:mysql://furseal-mysql:3306/furseal?createDatabaseIfNotExist=true
#    url: jdbc:mysql://10.111.16.3:3306/furseal?createDatabaseIfNotExist=true
#    url: ${DB_URL}
#    username: root
#    password: Kyo77437743
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9000

keycloak:
  jwk: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/certs

logging:
  level:
    org:
      springframework:
        security: INFO
      zalando:
        logbook: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"

my:
  message: default-message



